(define (for var start end step body env)
  (define (iter)
    (if (>= var end)
	null
	(begin (eval exp)
	       (set! var (+ var step))
	       (exp)
	)
    )
  )
  (begin (eval-definition "define "var" "start env)
    (iter)
  )
)
