(define rand
  (let ((x random-init))
    (define (generate)
      (begin (set! x (rand-update x))
	     x
      )
    )
    (define (reset val)
	(set! x val)
    )
    (define (dispatch msg)
	(cond ((eq? msg 'generate)     generate)
	      ((eq? msg 'reset)     reset)
	      (else     (begin (display "Unknown message")
			       (newline)
			)
	      )
	)
    )
  )
)
